// import LocalizedStrings from 'react-native-localization';

const strings = {
  en:{
    LOGIN: 'Login',
    SKIP: 'Skip',
    EMAIL_USERNAME: 'Email ID/Username',
    PASSWORD: 'Password',
    OR: 'or',
    FORGET_PASSWORD: 'Forgot Password?',
    FORGOT_PASS: 'Forgot Password',
    DONT_HAVE_ACCOUNT: 'Don’t have an account? ',
    SIGN_UP_HERE: 'Sign Up Here',
    SIGN_UP: 'Sign Up',
    SIGN_IN: 'Sign In',
    ALREADT_HAVE_ACCOUNT: 'Already have an account?',
    SIGN_IN_HERE: ' Sign In Here ',
    OTP: 'OTP',
    DIDNT_RECIEVED_CODE: 'Didn’t recieve a verification code?',
    RESEND_CODE: 'Resend Code',
    USERNAME: 'Username',
    EMAIL: 'Email',
    MOBILE: 'Mobile Number',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Passowrd',
    CONTINUE: 'Continue',
    RECENT_COMMENT: 'Most Recent Comments',
    MY_COUPONS: 'My Coupons',
    SUBMIT: 'Submit',
    PHONE_NUMBER: 'Phone Number',
    USE: 'Use',
    FEATURED: 'Featured',
    noLabelFoundError: 'No label found',
    emailCannotBeEmpty: "Email field can not be empty.",
    email50length: "Email field can not be more than 50 characters.",
    enterValidEmail: "Please enter a valid email address.",
    passwordCannotBeEmpty: "Password field can not be empty.",
    password6length: "Password field should be alteast 6 characters",
    nameCannotBeEmpty: "Name field can not be empty.",
    name25length: "Name field can not be more than 25 characters.",
    phoneCannotBeEmpty: "Phone number field can not be empty.",
    countryCodeCannotBeEmpty: "Country code field can not be empty.",
    phone10length: "Phone number field can not be more than 10 characters.",
    enterValidPhone: "Please enter a valid phone number.",
    confirmPassCannotBeEmpty: "Confirm password field can not be empty.",
    confirmPass6length: "Password should be alteast 6 characters",
    passwordMatch: "Password and confirm password should be same.",
    noTabFound: "No tab found with given id.",
    screenNotFoundInTab: "Screen not found with given selected tab.",
    all: "All",
    map: "Map",
    calendar: "Calendar",
    searchHint: "Search item here",
    add: "Add",
    noEventsAvail: 'No result found',
    apply: 'Apply',
    location: 'Location',
    distance: 'Distance',
    category: 'Categories',
    cost: 'Cost',
    dateRange: 'Date Range',
    eventHost: 'Event Host',
    filterDistance: 'Up to 100 miles from location entered',
    start: 'Start',
    end: 'End',
    saveLocation: 'Save Location',
    noEventsFound: 'No result found',
    remove: 'Remove',
    addLocation: 'Add New Location',
    yourLocation: 'Your Location',
    next: 'Next',
    nameShouldNotContainSpecialCh: 'Special character not allowed in name',
    password20length: 'Password should not be greater than 20 characters',
    otpSuccess: 'Otp sent successfully',
    errorEnterOtp: "Please enter valid OTP",
    emailEneterText: "Please enter your registered email id to receive OTP",
    posts: 'Posts',
    followers: 'Followers',
    following: 'Following',
    message: 'Message',
    noResultFound: 'No result found',
    noPostsAvailable: 'No Posts Available',
    selectLocationErr: "Error while fetching address. Please select your location",
    wentWrong: "Something went wrong. Please try again later",
    search: 'Search',
    lacationAndDistance: 'Location and Distance',
    notification: 'Notifications',
    privacyAndSecurity: 'Privacy & Security',
    accontManagement: 'Account Management',
    logout: 'Logout',
    ok: 'Ok',
    select: 'Select',
    OPEN_LOCATION: "Please enable location of the device for working of GP Live.",
    errorFetchingLocationPermission: "Error fetching location permission",
    comingSoon: "This feature is coming soon",
    pph: "Point per Hours",
    date: "Date",
    time: "Time",
    address: "Address",
    estimatedPrice: "Estimate Price",
    tickets: "Website",
    internetCheck: "No Internet Connection.Please try again later",
    settings:"Settings",
    categoryText:"Category",
    venue:'Location / Venue',
    checkInMsgForSingleEvent:"We have found a nearby event to checkin. Please open the app to checkin to a event and start earning points.",
    checkInMsgForMultipleEvents:"We have found multiple events to checkin. Please open the app to checkin to a event and start earning points.",
    checkoutMsg:"You are checked out of the event.",
    checkLocation:"Please enable the location service",
    getting_Started:"Getting Started",
    name:"Name",
    email:"Email",
    phone:"Phone",
    password:"Password",
    confirm_password:"Confirm Password",
    sign_up:"Sign Up",
    or:"OR",
    user_account_verify:"User Account Verification",
    otp_direction:"Enter 4 digit otp sent on your mobile and email",
    submit:"Submit",
    DO_NOT_HAVE_AN_ACCOUNT:"Do not have an account ?",
    preferences:"Preferences",
    Appearance:"Appearance",
    Dark:"Dark",
    Light:"Light",
    Language:"Language",
    English:"English",
    Hindi:"Hindi",
    WhoAreYou:'Who Are You',
    PropertyOwner:"Property Owner",
    PropertySeeker:"Property Seekeer",
    GoNext:"Continue"
  },
  hi:{
    LOGIN: 'लॉग इन करें',
    SKIP: 'Skip',
    EMAIL_USERNAME: 'Email ID/Username',
    PASSWORD: 'Password',
    OR: 'or',
    FORGET_PASSWORD: 'Forgot Password?',
    FORGOT_PASS: 'Forgot Password',
    DONT_HAVE_ACCOUNT: 'Don’t have an account? ',
    SIGN_UP_HERE: 'Sign Up Here',
    SIGN_UP: 'Sign Up',
    SIGN_IN: 'Sign In',
    ALREADT_HAVE_ACCOUNT: 'Already have an account?',
    SIGN_IN_HERE: ' Sign In Here ',
    OTP: 'OTP',
    DIDNT_RECIEVED_CODE: 'क्या सत्यापन कोड प्राप्त नहीं होगा?',
    RESEND_CODE: 'पुन: कोड भेजे',
    USERNAME: 'Username',
    EMAIL: 'Email',
    MOBILE: 'Mobile Number',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Passowrd',
    CONTINUE: 'Continue',
    RECENT_COMMENT: 'Most Recent Comments',
    MY_COUPONS: 'My Coupons',
    SUBMIT: 'Submit',
    PHONE_NUMBER: 'Phone Number',
    USE: 'Use',
    FEATURED: 'Featured',
    noLabelFoundError: 'No label found',
    emailCannotBeEmpty: "Email field can not be empty.",
    email50length: "Email field can not be more than 50 characters.",
    enterValidEmail: "Please enter a valid email address.",
    passwordCannotBeEmpty: "Password field can not be empty.",
    password6length: "Password field should be alteast 6 characters",
    nameCannotBeEmpty: "Name field can not be empty.",
    name25length: "Name field can not be more than 25 characters.",
    phoneCannotBeEmpty: "Phone number field can not be empty.",
    countryCodeCannotBeEmpty: "Country code field can not be empty.",
    phone10length: "Phone number field can not be more than 10 characters.",
    enterValidPhone: "Please enter a valid phone number.",
    confirmPassCannotBeEmpty: "Confirm password field can not be empty.",
    confirmPass6length: "Password should be alteast 6 characters",
    passwordMatch: "Password and confirm password should be same.",
    noTabFound: "No tab found with given id.",
    screenNotFoundInTab: "Screen not found with given selected tab.",
    all: "All",
    map: "Map",
    calendar: "Calendar",
    searchHint: "Search item here",
    add: "Add",
    noEventsAvail: 'No result found',
    apply: 'Apply',
    location: 'Location',
    distance: 'Distance',
    category: 'Categories',
    cost: 'Cost',
    dateRange: 'Date Range',
    eventHost: 'Event Host',
    filterDistance: 'Up to 100 miles from location entered',
    start: 'Start',
    end: 'End',
    saveLocation: 'Save Location',
    noEventsFound: 'No result found',
    remove: 'Remove',
    addLocation: 'Add New Location',
    yourLocation: 'Your Location',
    next: 'Next',
    nameShouldNotContainSpecialCh: 'Special character not allowed in name',
    password20length: 'Password should not be greater than 20 characters',
    otpSuccess: 'Otp sent successfully',
    errorEnterOtp: "Please enter valid OTP",
    emailEneterText: "Please enter your registered email id to receive OTP",
    posts: 'Posts',
    followers: 'Followers',
    following: 'Following',
    message: 'Message',
    noResultFound: 'No result found',
    noPostsAvailable: 'No Posts Available',
    selectLocationErr: "Error while fetching address. Please select your location",
    wentWrong: "Something went wrong. Please try again later",
    search: 'Search',
    lacationAndDistance: 'Location and Distance',
    notification: 'Notifications',
    privacyAndSecurity: 'Privacy & Security',
    accontManagement: 'Account Management',
    logout: 'Logout',
    ok: 'Ok',
    select: 'Select',
    OPEN_LOCATION: "Please enable location of the device for working of GP Live.",
    errorFetchingLocationPermission: "Error fetching location permission",
    comingSoon: "This feature is coming soon",
    pph: "Point per Hours",
    date: "Date",
    time: "Time",
    address: "Address",
    estimatedPrice: "Estimate Price",
    tickets: "Website",
    internetCheck: "No Internet Connection.Please try again later",
    settings:"Settings",
    categoryText:"Category",
    venue:'Location / Venue',
    checkInMsgForSingleEvent:"We have found a nearby event to checkin. Please open the app to checkin to a event and start earning points.",
    checkInMsgForMultipleEvents:"We have found multiple events to checkin. Please open the app to checkin to a event and start earning points.",
    checkoutMsg:"You are checked out of the event.",
    checkLocation:"Please enable the location service",
    getting_Started:"शुरू करना",
    name:"नाम",
    email:"ईमेल",
    phone:"फ़ोन",
    password:"कुंजिका",
    confirm_password:"पासवर्ड की पुष्टि कीजिये",
    sign_up:"साइन अप करें",
    or:"या",
    user_account_verify:"उपयोगकर्ता खाता सत्यापन",
    otp_direction: "अपने मोबाइल और ईमेल पर भेजे गए 4 अंकों का ओटीपी दर्ज करें",
    submit:"जमा करें",
    DO_NOT_HAVE_AN_ACCOUNT:"क्या आपका कोई खाता नहीं है ?",
    preferences:"पसंद",
    Appearance:"दिखावट",
    Dark:'काला',
    Light:"सफेद",
    Language:"भाषा",
    English:"अंग्रेज़ी",
    Hindi:"हिन्दी",
    WhoAreYou:"तुम कौन हो",
    PropertyOwner:"सम्पत्ति का मालिक",
    PropertySeeker:"संपत्ति खोजें",
    GoNext:"आगे बढ़ो"
  }
  }

export default strings.en;


export const getLanguageString = (lang) => {
  return strings[lang]
}